"""
Knowledge base loading - context spec, examples, and schema.

All paths are resolved relative to the project root by default, but can be overridden.
"""
import json
import os
from pathlib import Path
from typing import Dict, List

# Default paths (relative to project root)
DEFAULT_KB_PATH = Path("kb_compiled/context_spec.md")
DEFAULT_SCHEMA_PATH = Path("kb_compiled/models_jsonschema.json")
DEFAULT_EXAMPLES_DIR = Path("examples")

# The six production few-shot examples
EXAMPLE_FILES = {
    "siriusred": "siriusred_workplan.json",
    "ki67": "ki67_workplan.json",
    "SMA": "SMA_workplan.json",
    "空泡": "空泡_workplan.json",
    "rnascope": "rnascope_workplan.json",
    "脂滴rgb": "脂滴rgb_workplan.json",
}


def load_context_spec(path: Path = None) -> str:
    """
    Load the compiled API context specification (markdown).

    This is the single source of truth for API documentation,
    used by both Clarifier and Generator agents.

    Args:
        path: Optional custom path (defaults to kb_compiled/context_spec.md)

    Returns:
        The context spec as a string
    """
    if path is None:
        path = DEFAULT_KB_PATH

    if not path.exists():
        raise FileNotFoundError(
            f"Context spec not found: {path}\n"
            f"Run the knowledge compiler to generate kb_compiled/ artifacts."
        )

    return path.read_text(encoding="utf-8")


def load_examples(examples_dir: Path = None) -> Dict[str, str]:
    """
    Load all six production few-shot example workplans.

    Args:
        examples_dir: Optional custom directory (defaults to examples/)

    Returns:
        Dict mapping example name → JSON string
    """
    if examples_dir is None:
        examples_dir = DEFAULT_EXAMPLES_DIR

    if not examples_dir.exists():
        raise FileNotFoundError(
            f"Examples directory not found: {examples_dir}\n"
            f"Expected to find the six workplan examples there."
        )

    examples = {}
    for name, filename in EXAMPLE_FILES.items():
        path = examples_dir / filename
        if not path.exists():
            # Tolerate filename drift between "<name>_workplan.json" and
            # "<name>.workplan.json" (the gold set has both conventions). Resolve by
            # base name so a naming mismatch can't silently break the whole pipeline.
            stem = filename.replace("_workplan.json", "").replace(".workplan.json", "")
            candidates = sorted(examples_dir.glob(f"{stem}*.json"))
            if candidates:
                path = candidates[0]
            else:
                raise FileNotFoundError(
                    f"Example workplan not found for '{name}': tried '{filename}' "
                    f"and '{stem}*.json' in {examples_dir}"
                )
        examples[name] = path.read_text(encoding="utf-8")

    return examples


def load_models_schema(path: Path = None) -> dict:
    """
    Load the compiled JSON schema for workplan validation.

    This schema is generated by the knowledge compiler and contains
    all the API definitions for segment methods, parameters, etc.

    Args:
        path: Optional custom path (defaults to kb_compiled/models_jsonschema.json)

    Returns:
        The schema as a dict
    """
    if path is None:
        path = DEFAULT_SCHEMA_PATH

    if not path.exists():
        raise FileNotFoundError(
            f"Models schema not found: {path}\n"
            f"Run the knowledge compiler to generate kb_compiled/ artifacts."
        )

    with open(path, encoding="utf-8") as f:
        return json.load(f)


def format_examples_for_prompt(examples: Dict[str, str]) -> str:
    """
    Format the example workplans for injection into the Generator prompt.

    Args:
        examples: Dict from load_examples()

    Returns:
        Formatted string with all examples separated by headers
    """
    parts = []
    for name, content in examples.items():
        parts.append(f"--- EXAMPLE: {name} ---\n{content}")
    return "\n\n".join(parts)